# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d995a75ee3632995e51758b7dc40c4b5"
name = "smart advisor2"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_customers,read_discounts,read_fulfillments,read_inventory,read_locations,read_marketing_events,read_orders,read_price_rules,read_products,write_customers,write_discounts,write_draft_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
